[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tos/linker.ld", "-C", "relocation-model=static", "-C", "link-arg=-no-pie"]
# run-qemu.sh ignores binary path (we boot from os.img).
runner = "bash run-qemu.sh"
